/*
Palette generated by Material Palette - materialpalette.com/blue/deep-orange

$primary-color-dark:   #1976D2
$primary-color:        #2196F3
$primary-color-light:  #BBDEFB
$primary-color-text:   #FFFFFF
$accent-color:         #FF5722
$primary-text-color:   #212121
$secondary-text-color: #757575
$divider-color:        #BDBDBD
*/

/*
var grey = {
  50: '#fafafa',
  100: '#f5f5f5',
  200: '#eeeeee',
  300: '#e0e0e0',
  400: '#bdbdbd',
  500: '#9e9e9e',
  600: '#757575',
  700: '#616161',
  800: '#424242',
  900: '#212121',
  A100: '#d5d5d5',
  A200: '#aaaaaa',
  A400: '#303030',
  A700: '#616161'
};
*/

import { createMuiTheme } from '@material-ui/core/styles';

// import purple from '@material-ui/core/colors/purple';
import yellow from '@material-ui/core/colors/yellow';
import deepOrange from '@material-ui/core/colors/deepOrange';
import blue from '@material-ui/core/colors/blue';
import indigo from '@material-ui/core/colors/indigo';
// import cyan from '@material-ui/core/colors/cyan';
import grey from '@material-ui/core/colors/grey';

// console.log('grey100 ', grey[100]);
// console.log('grey300 ', grey[300]);
// console.log('grey400 ', grey[400]);

// console.log('blue 100 ', blue[100]);
// console.log('blue 300 ', blue[300]);

// console.log('indigo 100 ', indigo[100]);
// console.log('indigo 300 ', indigo[300]);

// const backImage2 =
// 	'http://lh4.ggpht.com/w-9ruGKvMxcvzBn4hhRICkisIP5U05xD2bNthIWO8hb62h24zcMgj76LTdLA15sS8CFh9AQHioRLgNisR0TnftamgGmY=s0';

const backImage = 'images/home.jpg';

const baseTheme = createMuiTheme({
	palette: {
		primary: {
			c100: blue[100],
			c200: blue[200],
			light: blue[300],
			main: blue[500],
			dark: blue[700]
		},
		primaryJV: {
			c100: indigo[100],
			c200: indigo[200],
			light: indigo[300],
			main: indigo[500],
			dark: indigo[700]
		},
		secondary: {
			light: deepOrange[300],
			main: deepOrange[500],
			dark: deepOrange[700]
		},
		star: {
			light: yellow[300],
			main: yellow[500],
			dark: yellow[700]
		},
		grey: {
			light: grey[300],
			main: grey[500],
			dark: grey[700]
		},
		third: {
			c100: blue[100],
			light: blue[300],
			main: blue[500],
			dark: blue[700]
		}
	},
	typography: {
		fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
		fontSize: 14,
		fontWeightLight: 300,
		fontWeightRegular: 400,
		fontWeightMedium: 500
	},
	homeImage: {
		zIndex: -1,
		position: 'absolute',
		top: 0,
		left: 0,
		minWidth: '100%',
		minHeight: '480px',
		height: '50vh',
		// background: `url(${backImage}) center`,
		backgroundSize: 'cover',
		background: `linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url(${backImage})`,
		opacity: 1,
		'&:hover': {
			opacity: 0.5
		}
	},
	backgroundImage: {
		zIndex: -1,
		position: 'absolute',
		top: 0,
		left: 0,
		minWidth: '100%',
		minHeight: '480px',
		height: '100%',
		backgroundSize: 'cover',
		background: `linear-gradient(to right top, ${grey[100]}, ${grey[300]})`
		// background: 'linear-gradient(to right bottom, #430089, #82ffa1)'
		// background: `linear-gradient(to right top, ${indigo[100]}, ${indigo[300]})`
		// background: `linear-gradient(to right top, ${blue[100]}, ${blue[300]})`
		// background: 'linear-gradient(to bottom, #1BBB2 0%, #1BE1D6 100%)'
	},
	anchor: {
		main: blue[500],
		selected: blue[700]
	},
	text: {
		home: '#fff',
		header: 'rgba(4,24,53,.9)',
		main: '#3a3a3d'
	},
	drawerWidth: 240,
	topNavLineHeight: 32,
	boxShadow: {
		e4:
			'0px 2px 4px -1px rgba(0, 0, 0, 0.2), 0px 4px 5px 0px rgba(0, 0, 0, 0.14), 0px 1px 10px 0px rgba(0, 0, 0, 0.12)',
		e6:
			'0px 3px 5px -1px rgba(0, 0, 0, 0.2), 0px 6px 10px 0px rgba(0, 0, 0, 0.14), 0px 1px 18px 0px rgba(0, 0, 0, 0.12)',
		e8:
			'0px 5px 5px -3px rgba(0, 0, 0, 0.2), 0px 8px 10px 1px rgba(0, 0, 0, 0.14), 0px 3px 14px 2px rgba(0, 0, 0, 0.12)',
		e20:
			'0px 10px 13px -6px rgba(0, 0, 0, 0.2), 0px 20px 31px 3px rgba(0, 0, 0, 0.14), 0px 8px 38px 7px rgba(0, 0, 0, 0.12)'
	},
	primary: {
		base: '#1f8dd6',
		darkColor: '#2d3e50',
		light: '#3ba0e3',
		dark: '#1a76b2',
		tinted: '#3598da',
		shaded: '#1c7fc1'
	},
	// header: { base: '#2d3e50', text: '#ffffff', select: '#b6def9' },
	features: { base: '#ebebeb', text: '#1f8dd6', select: '#b6def9', itemBase: '#ffffff', pText: '#2d3e50' },
	login: {
		base: '#ffffff',
		splash: '#1f8dd6',
		select: '#156193',
		darkColor: '#2d3e50',
		inputText: '#3f5771',
		separator: '#5b7da2',
		facebook: '#3b5998',
		facebookSelected: '#2d4373',
		google: '#4285f4',
		googleSelected: '#1266f1',
		textBorder: '#cccccc',
		boxShadow: '#eaeaea'
	}
});

// console.log('baseTheme ', baseTheme);

export { baseTheme as appTheme };

// const baseTheme2 = createMuiTheme({
// 	palette: {
// 		primary: { main: purple[500] },
// 		secondary: { main: cyan[500] }
// 	},
// 	typography: {
// 		fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
// 		fontSize: 14,
// 		fontWeightLight: 300,
// 		fontWeightRegular: 400,
// 		fontWeightMedium: 500
// 	}
// });

// const baseThemeSave = createMuiTheme({
// 	palette: {
// 		primary: { main: blue[500] },
// 		secondary: { main: cyan[500] }
// 	},
// 	typography: {
// 		fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
// 		fontSize: 14,
// 		fontWeightLight: 300,
// 		fontWeightRegular: 400,
// 		fontWeightMedium: 500
// 	}
// });

// const baseTheme3 = createMuiTheme({
// 	palette: {
// 		primary: { main: purple[500] }, // Purple and green play nicely together.
// 		secondary: { main: '#11cb5f' } // This is just green.A700 as hex.
// 	},
// 	typography: {
// 		fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
// 		fontSize: 14,
// 		fontWeightLight: 300,
// 		fontWeightRegular: 400,
// 		fontWeightMedium: 500
// 	}
// });

// sidebar: {
// 	base: '#2d3e50',
// 	headerText: '#4b7197',
// 	text: '#1f8dd6',
// 	button: '#6fbef3',
// 	buttonActive: '#ffffff',
// 	searchText: '#ffffff',
// 	searchIconColor: '#ffffff',
// 	searchIconHoverColor: '#1f8dd6',
// 	settingsIconColor: '#4b7197',
// 	settingsIconHoverColor: '#ffffff'
// },
// navMenu: { open: '#000000', close: '#ffffff' },
// settings: {
// 	base: '#ffffff',
// 	textBorder: '#cccccc',
// 	boxShadow: '#eaeaea',
// 	darkColor: '#2d3e50',
// 	subscriptionTitleColor: '#2d3e50',
// 	subscriptionTitleTextColor: '#ffffff',
// 	subscriptionUrl: '#1f8dd6'
// },
// dashboard: {
// 	text: '#2d3e50',
// 	iconColor: '#2d3e50',
// 	iconHoverColor: '#1f8dd6',
// 	subscriptionTitleColor: '#2d3e50',
// 	subscriptionTitleTextColor: '#ffffff',
// 	articleHeaderColor: '#1f8dd6',
// 	articleHeaderHoverColor: '#2d3e50',
// 	footer: '#2d3e50',
// 	footerText: '#ffffff'
// },
// introduction: { base: '#1f8dd6', text: '#ffffff' }
