// data actions

export const GET_USER_DATA = 'GET_USER_DATA';
export const SEARCH_USER_DATA = 'SEARCH_USER_DATA';

export const MOVE_USER_OBJECT = 'MOVE_USER_OBJECT';

export const ADD_USER_GOAL = 'ADD_USER_GOAL';

export const DELETE_USER_GOAL = 'DELETE_USER_GOAL';
export const CLONE_USER_GOAL = 'CLONE_USER_GOAL';
export const UPDATE_USER_GOAL = 'UPDATE_USER_GOAL';

export const ADD_USER_PROJECT = 'ADD_USER_PROJECT';
export const DELETE_USER_PROJECT = 'DELETE_USER_PROJECT';
export const CLONE_USER_PROJECT = 'CLONE_USER_PROJECT';
export const UPDATE_USER_PROJECT = 'UPDATE_USER_PROJECT';

export const ADD_USER_TASK = 'ADD_USER_TASK';
export const DELETE_USER_TASK = 'DELETE_USER_TASK';
export const MOVE_USER_TASK_PROJECT = 'MOVE_USER_TASK_PROJECT';
export const CLONE_USER_TASK = 'CLONE_USER_TASK';
export const UPDATE_USER_TASK = 'UPDATE_USER_TASK';

export const UPDATE_USER_DATE_TASK = 'UPDATE_USER_DATE_TASK';
export const UPDATE_USER_DATES_TASK = 'UPDATE_USER_DATES_TASK';

export const ADD_USER_TASK_TAG = 'ADD_USER_TASK_TAG';
export const DELETE_USER_TASK_TAG = 'DELETE_USER_TASK_TAG';
export const MOVE_USER_TASK_TAG = 'MOVE_USER_TASK_TAG';
